//     categories: ['rest', 'work', 'kitchen', 'children', 'bath],

import { Product } from '@/lib/types'

export const products: Product[] = [
  {
    name: 'Chandelier VODA',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'The base made of polished stainless steel gives an original floating effect.',
    price: 450,
    priceBeforeDiscount: 670,
    id: 1,
    discount: true,
    categories: ['kitchen', 'bath'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: true,
    cartAmount: null,
    favorite: true,
  },
  {
    name: 'Sofa RONALD',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'The model is characterized by simplicity of lines and shapes, without flashy decor.',
    price: 1560,
    priceBeforeDiscount: 1980,
    id: 2,
    discount: true,
    categories: ['rest', 'children', 'work'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: true,
    cartAmount: null,
    favorite: false,
  },
  {
    name: 'Chest of Drawers VENT',
    imgSrc: '/assets/images/top_background.jpg',
    description: 'European oak is particularly strong and stable.',
    price: 340,
    priceBeforeDiscount: 450,
    id: 3,
    discount: true,
    categories: ['rest', 'work', 'children'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: false,
    cartAmount: null,
    favorite: true,
  },
  {
    name: 'Bed TATRAN',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'The base made of polished stainless steel gives an original floating effect.',
    price: 1200,
    priceBeforeDiscount: null,
    id: 4,
    discount: false,
    categories: ['rest', 'children'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: false,
    cartAmount: null,
    favorite: false,
  },
  {
    name: 'Armchair VILORA',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'Soft and cozy, neat and stylish. Resilient seat cushions and pleasant-to-touch fabric.',
    price: 210,
    priceBeforeDiscount: null,
    id: 5,
    discount: false,
    categories: ['rest', 'work', 'children'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: false,
    cartAmount: null,
    favorite: false,
  },
  {
    name: 'Table MENU',
    imgSrc: '/assets/images/top_background.jpg',
    description: 'To make dining enjoyable, you need the right dining table.',
    price: 340,
    priceBeforeDiscount: null,
    id: 6,
    discount: false,
    categories: ['kitchen'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: false,
    cartAmount: null,
    favorite: false,
  },
  {
    name: 'Armchair ASKESTA',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'Highly elastic polyurethane foam inside the chair is reliable and durable.',
    price: 680,
    priceBeforeDiscount: null,
    id: 7,
    discount: false,
    categories: ['rest', 'work', 'children'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: false,
    cartAmount: null,
    favorite: false,
  },
  {
    name: 'Table NORMAN',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'Perfectly withstands sunlight, humidity changes, and any precipitation.',
    price: 400,
    priceBeforeDiscount: null,
    id: 8,
    discount: false,
    categories: ['kitchen'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: false,
    cartAmount: null,
    favorite: false,
  },
  {
    name: 'Sofa NASTAN',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'The model is characterized by simplicity of lines and shapes, without flashy decor.',
    price: 800,
    priceBeforeDiscount: null,
    id: 9,
    discount: false,
    categories: ['rest', 'work', 'children'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: false,
    cartAmount: null,
    favorite: false,
  },
  {
    name: 'Sofa ASKETA',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'Thanks to the snap mechanism, the sofa easily transforms into a comfortable bed.',
    price: 680,
    priceBeforeDiscount: null,
    id: 10,
    discount: false,
    categories: ['rest', 'work', 'children'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: false,
    cartAmount: null,
    favorite: false,
  },
  {
    name: 'Armchair LUNAR',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'Perfectly withstands sunlight, humidity changes, and any precipitation.',
    price: 400,
    priceBeforeDiscount: null,
    id: 11,
    discount: false,
    categories: ['rest', 'work', 'children'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: false,
    cartAmount: null,
    favorite: false,
  },
  {
    name: 'Wardrobe Nastan',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'The furniture can be equipped with a variety of lighting systems.',
    price: 800,
    priceBeforeDiscount: null,
    id: 12,
    discount: false,
    categories: ['rest', 'work', 'children'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: false,
    cartAmount: null,
    favorite: true,
  },
]

export const cartList: Product[] = [
  {
    name: 'Chandelier VODA',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'The base made of polished stainless steel gives an original floating effect.',
    price: 450,
    priceBeforeDiscount: 670,
    id: 1,
    discount: true,
    categories: ['kitchen', 'bath'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: true,
    cartAmount: null,
    favorite: true,
  },
  {
    name: 'Sofa RONALD',
    imgSrc: '/assets/images/top_background.jpg',
    description:
      'The model is characterized by simplicity of lines and shapes, without flashy decor.',
    price: 1560,
    priceBeforeDiscount: 1980,
    id: 2,
    discount: true,
    categories: ['rest', 'children', 'work'],
    cartImgSrc: '/assets/images/cart_1.jpg',
    inTheCart: true,
    cartAmount: null,
    favorite: false,
  },
]
